### ISSUE TITLE
Wrong description for tool_opencast | apiconnecttimeout

### ISSUE THREAD

**Issue by qmex-mp** [Opencast-Moodle/moodle-tool_opencast#49]
This took me a few hours (together with a second Bug I will post in a few minutes) to find out.
The description in the Administration is wrong:
![image](https://user-images.githubusercontent.com/8076291/164014637-9606a957-019f-4510-9e4d-09fe09544610.png)

Here the given definition is "time in seconds" but this is wrong as we can see if we look into the classes/local/api.php in line 221:
`
     $this->setopt(array(
            'CURLOPT_TIMEOUT_MS' => $this->timeout,
            'CURLOPT_CONNECTTIMEOUT_MS' => $this->connecttimeout));
    }
`
It should be milisenconds, and 500ms is way to low for this as Linux Systems with an Server optimized Kernel (lower tickrate) doenst work with something in curl under one ms (Error: timeout of 500 too small to resolve via SIGALRM method)

**Comment by jojoob** [comment]
The german description is indeed wrong (/outdated since #42). In English it's:

> Configure the time in milliseconds while Moodle is trying to connect to Opencast. If Opencast does not answer within this time, the connection attempt times out.

But the German lang file isn't bundled with the plugin but instead provided via the German Moodle language pack:

* https://docs.moodle.org/400/en/Language_packs
* https://docs.moodle.org/dev/Translation
* https://lang.moodle.org/

Regarding the SIGALRM error, I was not able to reproduce this on my test machine but this seems to be a known limitation under specific circumstances: https://curl.se/libcurl/c/CURLOPT_TIMEOUT_MS.html

> If libcurl is built to use the standard system name resolver, that portion of the transfer will still use full-second resolution for timeouts with a minimum timeout allowed of one second.
> 
> In unix-like systems, this might cause signals to be used unless [CURLOPT_NOSIGNAL](https://curl.se/libcurl/c/CURLOPT_NOSIGNAL.html) is set.

**Comment by mwuttke** [comment]
@qmex-mp: I've changed the german language string for _connecttimeout_ on [https://lang.moodle.org/](https://lang.moodle.org) from _Sekunden_ to _Millisekunden_
