### ISSUE TITLE
Video is not displayed with plugin, only with external link Opencast

### ISSUE THREAD

**Issue by dasarro23** [Opencast-Moodle/moodle-tool_opencast#53]
Once the Opencast plugin (latest version in both cases) is installed, we have a problem when incorporating videos into the courses.

Access to the api is correct and the test is valid, but when we embed a video it is displayed in black, instead if we use the full URL it is displayed.

Via embedded link (KO):

Request 1 - HTTP 206: https://opencastdes.example.com/admin-ng/login.html;jsessionid=node011nd9gpj0yki8a3ymyemvixda49695670.node0
Request 2 - HTTP 302: https://opencastdes.example.com/api/events/db4fc5f0-47e1-43b8-b409-93bb7c8f4763

Via external link (OK):

HTTP 200 - https://opencastdes.example.com/static/mh_default_org/api/5f54f0d8-71d8-49f4-afc7-a89c60730791/68c40c8b-7197-4653-af15-f3d8e632bbdd/3_4_3__Folder.mp4

Any ideas?

Visualization and direct access to OpenCast has no problem, we only have it through the Moodle plugin.

The config.json configuration files have not been modified.

Thanks!
![video_not_view_black](https://user-images.githubusercontent.com/32614096/168024767-2eaf2cbf-be8c-4c77-ac90-f9535fc919d2.jpg)
!

**Comment by justusdieckmann** [comment]
Hey @dasarro23,

I am currently going through older issues. I'm sorry that your issue was apparently missed. 

Is this issue still relevant for you? I would close it for now, but if it is, please do reopen this issue and tell me: which two opencast plugins have you installed and how exactly do you embed videos?

Justus
